trigger:
- master

pool:
  name: 'default'

variables:
  buildConfiguration: 'Release'
  deployPath: 'C:\inetpub\wwwroot\BuscandoMiTrago' # Your IIS deployment path

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\publish'
    zipAfterPublish: false

- task: ArchiveFiles@2
  displayName: 'Create Deployment ZIP'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\publish'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
    replaceExistingArchive: true

- task: PowerShell@2
  displayName: 'Deploy to IIS'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Stopping IIS Site..."
      Stop-WebSite -Name "BuscandoMiTrago"
      
      Write-Host "Preparing deploy folder..."
      if (Test-Path "$(deployPath)") {
          Remove-Item -Path "$(deployPath)\*" -Recurse -Force
      } else {
          New-Item -Path "$(deployPath)" -ItemType Directory -Force
      }
      
      Write-Host "Extracting WebApp.zip to deploy folder..."
      Expand-Archive -Path "$(Build.ArtifactStagingDirectory)\WebApp.zip" -DestinationPath "$(deployPath)" -Force
      
      Write-Host "Starting IIS Site..."
      Start-WebSite -Name "BuscandoMiTrago"
