trigger:
- master

pool:
  name: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  deployPath: 'C:\inetpub\wwwroot\BuscandoMiTrago' # Set your IIS deployment path

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Deploy to IIS'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Stopping IIS Site..."
      Stop-WebSite -Name "BuscandoMiTrago"
      
      Write-Host "Preparing deploy folder..."
      if (Test-Path "$(deployPath)") {
          Remove-Item -Path "$(deployPath)\*" -Recurse -Force
      } else {
          New-Item -Path "$(deployPath)" -ItemType Directory -Force
      }
      
      Write-Host "Extracting WebApp.zip to temporary folder..."
      $tempDeployPath = "$(deployPath)-temp"
      if (Test-Path $tempDeployPath) { Remove-Item $tempDeployPath -Recurse -Force }
      Expand-Archive -Path "$(Build.ArtifactStagingDirectory)\WebApp.zip" -DestinationPath $tempDeployPath -Force
      
      Write-Host "Looking for the root folder 'WebApp' inside the temporary folder..."
      $innerFolder = Join-Path $tempDeployPath "WebApp"
      if (Test-Path $innerFolder) {
          Write-Host "Found inner folder: $innerFolder"
          Write-Host "Moving contents to deploy path: $(deployPath)"
          Move-Item -Path "$innerFolder\*" -Destination "$(deployPath)" -Force
          Remove-Item -Path $tempDeployPath -Recurse -Force
      }
      else {
          Write-Error "Folder 'WebApp' not found in extracted package. Check the ZIP structure."
      }
      
      Write-Host "Starting IIS Site..."
      Start-WebSite -Name "BuscandoMiTrago"
