trigger:
- master

pool:
  name: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  deployPath: 'C:\inetpub\wwwroot\BuscandoMiTrago' # Set your IIS deployment path

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Deploy to IIS'
  inputs:
    targetType: 'inline'
    script: |
      # Stop the IIS Site before deploying
      Stop-WebSite -Name "BuscandoMiTrago"

      # Ensure the deploy folder exists
      if (Test-Path "$(deployPath)") {
          Remove-Item -Path "$(deployPath)\*" -Recurse -Force
      } else {
          New-Item -Path "$(deployPath)" -ItemType Directory -Force
      }

      # Extract files correctly from the ZIP
      Expand-Archive -Path "$(Build.ArtifactStagingDirectory)\WebApp.zip" -DestinationPath "$(deployPath)-temp" -Force

      # Find the actual deployed folder inside the extracted directory
      $extractedFolder = Get-ChildItem -Path "$(deployPath)-temp" | Where-Object { $_.PSIsContainer } | Select-Object -ExpandProperty FullName

      # Move all files to the correct deployment path
      if ($extractedFolder) {
          Move-Item -Path "$extractedFolder\*" -Destination "$(deployPath)" -Force
          Remove-Item -Path "$(deployPath)-temp" -Recurse -Force
      }

      # Start the IIS Site
      Start-WebSite -Name "BuscandoMiTrago"

