trigger:
- master

pool:
  name: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  deployPath: 'C:\inetpub\wwwroot\BuscandoMiTrago' # Set your IIS deployment path

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Deploy to IIS'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Stopping IIS Site..."
      Stop-WebSite -Name "BuscandoMiTrago"
      
      Write-Host "Preparing deploy folder..."
      if (Test-Path "$(deployPath)") {
          Remove-Item -Path "$(deployPath)\*" -Recurse -Force
      } else {
          New-Item -Path "$(deployPath)" -ItemType Directory -Force
      }
      
      # Define temporary extraction folder
      $tempDeployPath = "$(deployPath)-temp"
      if (Test-Path $tempDeployPath) { Remove-Item $tempDeployPath -Recurse -Force }
      
      Write-Host "Extracting WebApp.zip to temporary folder: $tempDeployPath"
      Expand-Archive -Path "$(Build.ArtifactStagingDirectory)\WebApp.zip" -DestinationPath $tempDeployPath -Force
      
      Write-Host "Listing contents of temporary folder:"
      Get-ChildItem -Path $tempDeployPath -Recurse | ForEach-Object { Write-Host $_.FullName }
      
      # Get all items in the temporary folder
      $items = Get-ChildItem -Path $tempDeployPath
      
      if (($items | Where-Object { $_.PSIsContainer }).Count -eq 1 -and $items.Count -eq 1) {
          # Only one folder exists, assume that's the container folder
          $innerFolder = $items[0].FullName
          Write-Host "Found single container folder: $innerFolder"
          Write-Host "Moving contents from $innerFolder to $(deployPath)"
          Move-Item -Path "$innerFolder\*" -Destination "$(deployPath)" -Force
      }
      else {
          Write-Host "Moving all contents from $tempDeployPath to $(deployPath)"
          Move-Item -Path "$tempDeployPath\*" -Destination "$(deployPath)" -Force
      }
      
      Write-Host "Removing temporary folder..."
      Remove-Item -Path $tempDeployPath -Recurse -Force
      
      Write-Host "Starting IIS Site..."
      Start-WebSite -Name "BuscandoMiTrago"

